### ISSUE TITLE
Pulling Osiris on an AKS cluster

### ISSUE THREAD

**Issue by rbitia** [deislabs/osiris#7] opened 2018-12-12 01:54 UTC
---

### Environment summary

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Osiris Version
latest
Install Method (e.g. k8s YAMLs, Helm Chart)
helm chart
### Issue Details
The images go in pull back off errors.
### Repo Steps
Used the readme instructions 
After installing the chart do a 'helm repo up' to work around the issue.

**Comment by yaron2** [comment] 2018-12-12 02:35
I can't reproduce.. can you see any error messages when describing the pod with kubectl describe pod?

**Comment by krancour** [comment] 2018-12-12 15:35
@rbitia I know you were dealing with this issue for most of yesterday. I was under the impression is was resolved.

I'm also confused by your steps for reproducing since they seem to document a workaround (for an issue we cannot reproduce in the first place).

I'm wondering if what you were attempting to do here was document a known issue, in case others encounter it, along with resolution? If so, `helm repo up` resolved _your_ problem because it pulled the latest version of the chart, replacing an older version that you already had cached locally. Brand new users following the instructions in the readme should not encounter any issue at all.

**Comment by krancour** [comment] 2018-12-12 23:58
I spoke with @rbitia and this issue was an FYI for others running into this. Really, new users who follow the readme should _not_ encounter this. Closing.

**Closed by krancour** 2018-12-12 23:58 UTC
